language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

notifications:
  email: false

sudo: false